name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.9
    - name: Install dependencies
      run: |
        make install
        python -m textblob.download_corpora
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    - name: Build the Docker image
      run: |
        make build
    - name: Push the Docker image to Docker Hub
      run: |
        #make push
